---
title: "Pre-Course Self Reflection 1"
author: "Sofia Urgoiti Crespo (she/her)"
date: 2024-01-08
editor_options: 
  chunk_output_type: console
---

# I. Some questions about school and life:

*Where are you coming from (e.g. “I recently finished my undergraduate degree”, “I’ve been working in industry X for Y years”) (1-2 sentences)*

Prior to starting my Master's at UCSB, I completed my Bachelor's in Ecological & Environmental Sciences at The University of Edinburgh (Scotland, UK), where I graduated in 2021. I then received a Fulbright Scholarship from the Spanish government, which allowed me to pursue my Master's here at UCSB starting in September 2022.

*What do you hope to get out of this class? (3-4 sentences)*

I am a part of Jenn Caselle's lab, and my research revolves around spatiotemporal variability of kelp biomass in the Channel Islands. As I am working on my Master's Thesis, I have realised I lack a systematic/organised way to create and store my figures. I am hoping to learn how to produce appealing and publication-worthy figures, with a consistent format. One particular goal I have in mind is to learn how to develop a function that standardizes my figures format at the top of my scripts. 

*If you have a particular career goal in mind, how does this course apply to your future career, if at all? (1-3 sentences)*

After completing my Master's at UCSB, I envision myself working in the industry, whether that is the NGO sector, the consulting world, or the science communication field. I feel the need to explore life "outside" academia, as I haven't had a lot of time in between my Bachelor's and my Master's.

*What do you wish your instructors knew about you, but don’t? (2-4 sentences)*

1. I am an international student from Spain, and adjusting to the US university system & expectations has been quite the challenge (although I am getting the hang of it by now!).

2. I am going through a rough patch after the recent end of a long-term relationship, and I expect it to impact my performance for a few months. I will try my best, since university will give me the purpose I need to move on. 


#II. Some questions about the way you like to learn:

*What kinds of assignments, skills, or behaviors have you felt most comfortable with / enjoy from past classes? Why do you enjoy them? (4-5 sentences)*

The projects that I have found most enjoyable in the past have had a creative aspect to them such as storytelling/creating blog posts. I remember in particular having to "translate" a scientific paper to the language of the wider public. Having somewhat of a creative mind and a sensitive personality, I enjoy exploring different ways of communication. I  also modeling projects relevant to my field (Marine Sciences), notably a modeling exercise we had to do last quarter which entailed predicting aquaculture potential along the  California coastline. I believe modeling is an area I am actively working to improve, so I get excited when I get to practice it in class.  

*How confident do you feel in your data visualization skills? Why? (3-4 sentences)*

After taking the "Geospatial Analysis" course taught by Ruth Oliver this past Fall, my confidence in data visualization and map making has increased significantly! I am now confident with tmap as an alternative to ggplot for spatial data. When it comes to other data visualization techniques, I am confident in creating histograms, bar charts, anomaly plots, and faceting... but I could definitely brush up on my formatting and labeling skills (I never know how to deal with text/legends in figures).


*How confident do you feel in your coding skills (primarily R, but feel free to elaborate on any of the languages you’ve used)? Why? (3-4 sentences)*

I feel very confident in my data wrangling & exploration skills in R, but I recognise I can always improve my analysis skills (which is why I enrolled in ESM244). In terms of other languages, I have briefly been exposed to Google Earth Engine, Python and SQL although I would rate my confidence in these with a 30/100.


*What have you struggled with in the past in other graduate-level courses? Why? (3-4 sentences)*

I have struggled with keeping up with the pace of the course, since I consider myself a slow learner and I need time to digest material. A negative cycle I have fallen into sometimes is falling behind towards the midpoint of the quarter: once I fall behind I find it hard to reach out for help from peers or instructors. I have also found certain data group projects overwhelming, and that has mostly been due to "git conflicts" and never having been taught the theory of how to write code collaboratively. 

*Of the courses you’re taking this quarter, which do you expect to be the most challenging? Most demanding? (1-2 sentences)*

I am taking 2 other courses: a seminar compulsory for my program (MARSC595), and Advanced Data Analysis (ESM244). I believe the latter will be the most challenging since it is a survey course on a variety of analytical methods, including an intro on machine learning, text analysis, spatial tools... Because it encompasses many more topics than this course (which is more specific), some of them which I have never been exposed to, I expect to dedicate more time learning about concepts completely new to me.

*What responsibilities do you have outside of school, and how do you want to balance them? (3-4 sentences)*

I am lucky enough not to have a job commitment, as my funding is secured for the remaining of my program. I do mentor once/twice a month for a marine science outreach program for middle-school students (Sea the Future, through the Benioff Ocean Science Lab at UCSB). Being an international student does result in extra bureaucratic commitments, and I have had some issues with paperwork and visa extensions in the past, which have taken more time than expected. I am planning to solve all my visa issues within the next month so I can fully focus on my courses/research.  

*Which learning goals from the syllabus are you most excited about? (3-4 sentences)*

I am excited to explore the theory behind visual communication (the human psychology behind), which I remember you mentioned in this first lecture, as well as learning how to make my figures more inclusive by adopting a diversity perspective. I admit being guilty to copy pasting chunks of my previous figures/code, especially with the basics of ggplot, so I am excited to master writing code from scratch until it becomes muscle memory. 

*Most importantly, how do you plan on accomplishing your learning goals for this course? Note: be specific here! Instead of writing, “I will complete homework assignments” or “I will study”, you can make these more specific strategies: “I will create a schedule to map out assignments“ (elaborate on this), “I will use the homework assignments as opportunities to practice X,” I will communicate with classmates to ask for help after trying X,” “I will participate in online learning communities, such as TidyTuesday…” etc. (5-8 sentences)*


#III. Some fun questions:

*What activity(ies) (outside of school / work) brings you the most joy? How do you plan to incorporate that activity into your schedule this quarter (if at all)? If you are unable to do so, is there something else you can plan to do that will bring you similar joy? (3-5 sentences)*

Spending time in nature has been my cure in times of stress. I am a keen hiker, surfer, yogi and skater. I try to do yoga once a week, hike on the weekends, and surf whenever the forecast allows. If I have little chunks of time to spend indoors, I try to play some music (ukelele), write some poetry, or attempt to crochet (it is taking me longer than expected to get a hang of it).


*What is a piece of media you enjoyed recently? (e.g. music, book, movie, tweet, meme) (2-4 sentences)*

I recently listened to a podcast episode called "The Artist's Way", where Billy Chapata discusses how to channel the artist within you, build confidence in your skills/art, and the role of social media in the current art scene. Even though art is a hobby and not a profession to me, I thought this episode was very inspiring, and it made me think of an alternative future where I could have been a poet and not a researcher... Although I do not regret my choice!

Here is the link to the podcast, in case you want to check it out for yourself: 

https://open.spotify.com/episode/60wKIXj9I2k4TV3mLF7vel?fbclid=IwAR1uUASgOwmUUF7fKdGKQeRIA_FCpZj62bczgxl1geYf9xfIMAl_0w3VaDE
(Podcast: And then it hit me - by Cory Allen", speaker: Billy Chapata). 

